In [13]:
cells = [(row, '*', col, '=', row*col) 
         for row in range(1,10) 
         for col in range(1,10)]
for cell in cells:
    print(cell)

(1, '*', 1, '=', 1)
(1, '*', 2, '=', 2)
(1, '*', 3, '=', 3)
(1, '*', 4, '=', 4)
(1, '*', 5, '=', 5)
(1, '*', 6, '=', 6)
(1, '*', 7, '=', 7)
(1, '*', 8, '=', 8)
(1, '*', 9, '=', 9)
(2, '*', 1, '=', 2)
(2, '*', 2, '=', 4)
(2, '*', 3, '=', 6)
(2, '*', 4, '=', 8)
(2, '*', 5, '=', 10)
(2, '*', 6, '=', 12)
(2, '*', 7, '=', 14)
(2, '*', 8, '=', 16)
(2, '*', 9, '=', 18)
(3, '*', 1, '=', 3)
(3, '*', 2, '=', 6)
(3, '*', 3, '=', 9)
(3, '*', 4, '=', 12)
(3, '*', 5, '=', 15)
(3, '*', 6, '=', 18)
(3, '*', 7, '=', 21)
(3, '*', 8, '=', 24)
(3, '*', 9, '=', 27)
(4, '*', 1, '=', 4)
(4, '*', 2, '=', 8)
(4, '*', 3, '=', 12)
(4, '*', 4, '=', 16)
(4, '*', 5, '=', 20)
(4, '*', 6, '=', 24)
(4, '*', 7, '=', 28)
(4, '*', 8, '=', 32)
(4, '*', 9, '=', 36)
(5, '*', 1, '=', 5)
(5, '*', 2, '=', 10)
(5, '*', 3, '=', 15)
(5, '*', 4, '=', 20)
(5, '*', 5, '=', 25)
(5, '*', 6, '=', 30)
(5, '*', 7, '=', 35)
(5, '*', 8, '=', 40)
(5, '*', 9, '=', 45)
(6, '*', 1, '=', 6)
(6, '*', 2, '=', 12)
(6, '*', 3, '=', 18)
(6, '*', 4, '=', 24)
(6, '*', 5, '=', 30)
(6, '*', 6, '=', 36)
(6, '*', 7, '=', 42)
(6, '*', 8, '=', 48)
(6, '*', 9, '=', 54)
(7, '*', 1, '=', 7)
(7, '*', 2, '=', 14)
(7, '*', 3, '=', 21)
(7, '*', 4, '=', 28)
(7, '*', 5, '=', 35)
(7, '*', 6, '=', 42)
(7, '*', 7, '=', 49)
(7, '*', 8, '=', 56)
(7, '*', 9, '=', 63)
(8, '*', 1, '=', 8)
(8, '*', 2, '=', 16)
(8, '*', 3, '=', 24)
(8, '*', 4, '=', 32)
(8, '*', 5, '=', 40)
(8, '*', 6, '=', 48)
(8, '*', 7, '=', 56)
(8, '*', 8, '=', 64)
(8, '*', 9, '=', 72)
(9, '*', 1, '=', 9)
(9, '*', 2, '=', 18)
(9, '*', 3, '=', 27)
(9, '*', 4, '=', 36)
(9, '*', 5, '=', 45)
(9, '*', 6, '=', 54)
(9, '*', 7, '=', 63)
(9, '*', 8, '=', 72)
(9, '*', 9, '=', 81)

In [11]:
print('\n'.join([' '.join ('%dx%d = %2d' % (x, y, x * y)
                           for x in range(1, y + 1)) 
                 for y in range(1, 10)]))

1x1 =  1
1x2 =  2 2x2 =  4
1x3 =  3 2x3 =  6 3x3 =  9
1x4 =  4 2x4 =  8 3x4 = 12 4x4 = 16
1x5 =  5 2x5 = 10 3x5 = 15 4x5 = 20 5x5 = 25
1x6 =  6 2x6 = 12 3x6 = 18 4x6 = 24 5x6 = 30 6x6 = 36
1x7 =  7 2x7 = 14 3x7 = 21 4x7 = 28 5x7 = 35 6x7 = 42 7x7 = 49
1x8 =  8 2x8 = 16 3x8 = 24 4x8 = 32 5x8 = 40 6x8 = 48 7x8 = 56 8x8 = 64
1x9 =  9 2x9 = 18 3x9 = 27 4x9 = 36 5x9 = 45 6x9 = 54 7x9 = 63 8x9 = 72 9x9 = 81

In [14]:
k=[1,2,3,4,5,6,7,8,9]

for i in k :
    for j in k:
        s = i * j
        print ('%d*%d = %d   ' %(i, j, s), end="")

    print('\n')

1*1 = 1   1*2 = 2   1*3 = 3   1*4 = 4   1*5 = 5   1*6 = 6   1*7 = 7   1*8 = 8   1*9 = 9

2*1 = 2   2*2 = 4   2*3 = 6   2*4 = 8   2*5 = 10   2*6 = 12   2*7 = 14   2*8 = 16   2*9 = 18

3*1 = 3   3*2 = 6   3*3 = 9   3*4 = 12   3*5 = 15   3*6 = 18   3*7 = 21   3*8 = 24   3*9 = 27

4*1 = 4   4*2 = 8   4*3 = 12   4*4 = 16   4*5 = 20   4*6 = 24   4*7 = 28   4*8 = 32   4*9 = 36

5*1 = 5   5*2 = 10   5*3 = 15   5*4 = 20   5*5 = 25   5*6 = 30   5*7 = 35   5*8 = 40   5*9 = 45

6*1 = 6   6*2 = 12   6*3 = 18   6*4 = 24   6*5 = 30   6*6 = 36   6*7 = 42   6*8 = 48   6*9 = 54

7*1 = 7   7*2 = 14   7*3 = 21   7*4 = 28   7*5 = 35   7*6 = 42   7*7 = 49   7*8 = 56   7*9 = 63

8*1 = 8   8*2 = 16   8*3 = 24   8*4 = 32   8*5 = 40   8*6 = 48   8*7 = 56   8*8 = 64   8*9 = 72

9*1 = 9   9*2 = 18   9*3 = 27   9*4 = 36   9*5 = 45   9*6 = 54   9*7 = 63   9*8 = 72   9*9 = 81